### ISSUE TITLE
Postchain 3 support

### ISSUE THREAD

**Issue by killerstorm** [chainofalliance/postchain-client-csharp#1]
Hi.

First, it would be good to clarify it's compatible with Postchain 2 / Rell 0.8. (Rell 0.8 is latest version of Rell which works with Postchain 2).

Postchain 3 changed transaction data structure and hash calculation.

Changes to data structures are fairly minimal: instead of custom ASN.1 definition for a transaction we simply use GTV array:

https://bitbucket.org/chromawallet/postchain-client/src/2f5b96f5eed5ef908906e4e427a7fd62cc427817/src/gtx/gtx.js?at=feature%2Fv3-missing-serialization#lines-44

(so e.g. GTX.ASN1Messages.GTXTransaction is no longer needed.)

Hashing code is unfortunately quite complex. One problem is that it's more complex than strictly necessary to do hashing. There are, basically three layers:

1. Tree-ification of GTV: arrays and dictionaries are converted to binary trees in a deteriministic fashion.
2. Hash calculation: hashing walks the tree and calculates hashes. This is actually quite trivial.
3. Proofs: some special format which allows us to send only a part of GTV while incorporating a proof that this part belongs go the whole (i.e. that if you hash it with the rest it will give the same hash).

Support for proofs is only needed for crosschain ft3 transactions, which is kinda important in practice but not 100% necessary.

So, Kotlin code might be easier to follow & port as it has types: https://bitbucket.org/chromawallet/postchain2/src/master/postchain-base/src/main/kotlin/net/postchain/gtv/merkle/

But JS port is simpler as it skips some generics I think: https://bitbucket.org/chromawallet/postchain-client/src/2f5b96f5eed5ef908906e4e427a7fd62cc427817/src/gtv/merkle/?at=feature%2Fv3-missing-serialization

**Comment by Cherden** [comment]
Added in [v0.3](https://github.com/Cherden/postchain-client/releases/tag/v0.3)
